---
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Author: Marcelo Perazolo <mperazol@us.ibm.com>
#---

- name: installs prereq packages
  package:
    name: "{{ kibana_pre_packages }}"
    state: present
  register: install_preq
  until: install_preq is success
  retries: 5
  delay: 2

- name: add Kibana apt keys
  apt_key:
    url: "{{ item.url }}"
    state: "{{ item.state }}"
  with_items: "{{ kibana_keys }}"
  when:
      - kibana_keys is defined
      - ansible_os_family == 'Debian'
      - ansible_architecture == 'x86_64'
  register: add_keys_url
  until: add_keys_url is success
  retries: 5
  delay: 2

- name: add Kibana apt repositories
  apt_repository:
    repo: "{{ item.repo }}"
    state: "{{ item.state }}"
  with_items: "{{ kibana_repos }}"
  when:
      - kibana_repos is defined
      - ansible_os_family == "Debian"
      - ansible_architecture == 'x86_64'
  register: add_repos
  until: add_repos is success
  retries: 5
  delay: 2

- name: add Kibana rpm keys
  rpm_key:
    key: "{{ item.url }}"
    state: "{{ item.state }}"
  with_items: "{{ kibana_keys }}"
  when:
      - kibana_keys is defined
      - ansible_os_family == "Redhat"
      - ansible_architecture == 'x86_64'
  register: add_keys_url
  until: add_keys_url is success
  retries: 5
  delay: 2
  tags:
    - kibana-keys
    - kibana-pre-install

- name: add Kibana rpm repositories
  yum_repository:
    name: "{{ item.name }}"
    description: "{{ item.description }}"
    baseurl: "{{ item.url }}"
    gpgkey: "{{ item.gpgkey }}"
    gpgcheck: yes
  with_items: "{{ kibana_repos }}"
  when:
      - kibana_repos is defined
      - ansible_os_family == "Redhat"
      - ansible_architecture == 'x86_64'
  register: add_repos
  until: add_repos is success
  retries: 5
  delay: 2
