---
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Author: Marcelo Perazolo <mperazol@us.ibm.com>
#---

- name: copy ppc64le rpm package
  synchronize:
    src: "{{ repo_dir }}/{{ beat }}-{{ beats_version }}-1.ppc64le.rpm"
    dest: "/tmp"
    set_remote_user: no
  loop: "{{ beats }}"
  loop_control:
    loop_var: beat
    label: "{{ beat }}"
  when: ansible_architecture == 'ppc64le'
  delegate_to: "{{ my_repo }}"

- name: install ppc64le rpm package
  package:
    name: "/tmp/{{ beat }}-{{ beats_version }}-1.ppc64le.rpm"
    state: present
  register: rpm_install
  until: rpm_install is success
  retries: 5
  delay: 2
  loop: "{{ beats }}"
  loop_control:
    loop_var: beat
    label: "{{ beat }}"
  when: ansible_architecture == 'ppc64le'

- name: download x86_64 rpm file
  get_url:
    url: "{{ beats_url }}/{{ beat }}/{{ beat }}-{{ beats_version }}-x86_64.rpm"
    dest: "/tmp"
  register: rpm_download
  until: rpm_download is success
  retries: 5
  delay: 2
  loop: "{{ beats }}"
  loop_control:
    loop_var: beat
    label: "{{ beat }}"
  when: ansible_architecture == 'x86_64'

- name: install amd64 rpm package
  apt:
    deb: "/tmp/{{ beat }}-{{ beats_version }}-x86_64.rpm"
    state: present
  register: rpm_install
  until: rpm_install is success
  retries: 5
  delay: 2
  loop: "{{ beats }}"
  loop_control:
    loop_var: beat
    label: "{{ beat }}"
  when: ansible_architecture == 'x86_64'

